#!/usr/bin/perl -w

# Copyright 2013, Tomas Edwardsson 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


use LWP::Simple;
use XML::Simple;
use Data::Dumper;

if (!$ARGV[0]) {
	die "Nota retta rofa vinur, $0 <utskra>";
}
my $outfile = $ARGV[0];

our $gengi;

#my $gengi = XMLin(get('http://www.sedlabanki.is/gengi.asp'));
eval {
	$gengi = XMLin(get('http://www.sedlabanki.is/?PageID=289'));
};
if ($@) {
	print "Villa við að ná í gengi: $@\n";
	exit 1;
}

my $gengi_usd = 0;



open OUT, '>' . $outfile or
        die "Unable to open file for writing: $!";



foreach my $k (%{$gengi}) {
	if (ref($k) eq 'ARRAY') {
		foreach my $kk (@{$k}) {
			my $mn = $kk->{myntnafn};
			next if ($kk->{myntnafn} eq 'TWI' || ref $mn);
		
			$kk->{kaupgengi} =~ s/\./,/;
			$kk->{solugengi} =~ s/\./,/;
			if ($kk->{dagsetning} =~ /^(\d+)-(\d+)-(\d+)T/) {
				$kk->{dagsetning} = "$3.$2.$1";
			} else {
				die "Unknown date format (unparsable): \"$kk->{dagsetning}\"";
			}
			printf OUT ("%s;%s;%s;%s\r\n", $kk->{myntnafn}, $kk->{dagsetning}, $kk->{kaupgengi}, $kk->{solugengi});
		}
	}
}
close OUT;

exit 0;

